### Get all ingredients
GET localhost:8080/api/ingredients
Accept: application/json

### Get ingredients with pairing
GET localhost:8080/api/ingredient/1

### Get pairing with ingredients
GET localhost:8080/api/pairing/4

### Post new ingredient
POST http://localhost:8080/api/ingredient
Content-Type: application/json

{"ingredient":"chicken", "affinity1":"garlic, pasta, pesto","affinity2":"rice, beans, cheese","affinity3":"spinach, strawberry, poppy seed dressing"}


### Show Ingredients associated with Pairing
GET http://localhost:8080/api/pairing/4/ingredient

### Show all Pairings by name
GET http://localhost:8080/api/pairings/lemon


